name: Win app

on: [push]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.2'
          requirements: requirements
          upload_exe_with_name: HPE_collector_logs
          options: '--onefile, --name "HPE_collector_logs.exe", --windowed,'
