name: Build and Release Win app

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.2'
          spec: 'collect.py'
          requirements: 'requirements'
          upload_exe_with_name: HPE_collector_logs
          options: '--onefile, --name "HPE_collector_logs.exe", --windowed,'

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        id: tagging
        run: |
          $env:TAG ="v${{ github.run_number }}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.TAG }}
          generate_release_notes: true
          files: dist/HPE_collector_logs.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
